### ISSUE TITLE
NotImplementedError in Spree::Admin::OrdersController#cancel

### ISSUE THREAD

**Issue by anil826** [neerajkumar/spree-razorpay#1]
Cancel order is not working from admin panel.
![Screenshot 2019-10-12 at 5 08 37 PM](https://user-images.githubusercontent.com/7324027/66700826-f65d1380-ed12-11e9-9612-57ced0af2f75.png)

**Comment by anil826** [comment]
@neerajkumar Let me know if there is any fix for this issue I am also happy to help you on this but I didn't find any way.

**Comment by neerajkumar** [comment]
@anil826 I am looking into the issue. I will LYK.

**Comment by neerajkumar** [comment]
@anil826 It seems, It's not the issue with this gem, while it's breaking from `spee` gem. Please raise the issue with `spree` rubygem.
