### ISSUE TITLE
faceing issue in gem 'spree_razorpay'

### ISSUE THREAD

**Issue by navdeepdhamu** [neerajkumar/spree-razorpay#11]
Hi All,

i install the gem 'spree_razorpay'. when i run the (rails g spree_razorpay:install) commend then i faceing the "active_support.rb:80:in `block in load_missing_constant': uninitialized constant Spree::Preferences (NameError)"

please help me out

**Comment by neerajkumar** [comment]
@navdeepdhamu Please let me know that are you using this gem in your already setup spree rails application? Because, it will provide you a new Gateway of payment through razorpay.

**Comment by neerajkumar** [comment]
Closing because of no response.
