### ISSUE TITLE
Is this compatible with Solidus also (https://github.com/solidusio/solidus)

### ISSUE THREAD

**Issue by PlrEx** [neerajkumar/spree-razorpay#16]
I'm trying solidus and spree both

**Comment by neerajkumar** [comment]
No. Its not compatible with solidus because it uses lot of spree gem's methods. 
But, its a good idea to make another gem to support solidus too. 
Thanks :)

**Comment by neerajkumar** [comment]
@PlrEx  Created a new gem [solidus_razorpay](https://rubygems.org/gems/solidus_razorpay). 
https://github.com/neerajkumar/solidus-razorpay
