### ISSUE TITLE
Does this work with Solidus as well?

### ISSUE THREAD

**Issue by chakkizza** [neerajkumar/spree-razorpay#21]
Please let us know if this can work with Solidus as well. If not, can it be tweaked a bit to make it work. Thanks for all the help in advance.

**Comment by neerajkumar** [comment]
Good idea. 
Let me check.

**Comment by neerajkumar** [comment]
@chakkizza Created a new gem [solidus_razorpay](https://rubygems.org/gems/solidus_razorpay). 
https://github.com/neerajkumar/solidus-razorpay
